use crate::error::{HushError, Result};
use crate::ollama::{self, ChatChunk, ChatMessage, ChatStats, Health, ModelInfo, RunningModel};
use crate::state::{lock, AppState};
use crate::telemetry::TelemetrySample;
use crate::{
    EVENT_CHAT_CHUNK, EVENT_CHAT_DONE, EVENT_CHAT_ERROR, EVENT_CHAT_TOOL,
};
use futures_util::StreamExt;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use tauri::{AppHandle, Emitter, State};

// ---------------------------------------------------------------------------
// Connection + model management
// ---------------------------------------------------------------------------

#[tauri::command]
pub async fn ollama_health(state: State<'_, AppState>) -> Result<Health> {
    let (client, base_url) = (state.http.clone(), state.base_url());
    Ok(ollama::health(&client, &base_url).await)
}

#[tauri::command]
pub fn get_base_url(state: State<'_, AppState>) -> String {
    state.base_url()
}

#[tauri::command]
pub fn set_base_url(state: State<'_, AppState>, base_url: String) -> Result<String> {
    let trimmed = base_url.trim().trim_end_matches('/').to_string();
    if !(trimmed.starts_with("http://") || trimmed.starts_with("https://")) {
        return Err(HushError::Other(
            "base URL must start with http:// or https://".into(),
        ));
    }
    *lock(&state.base_url) = trimmed.clone();
    Ok(trimmed)
}

#[tauri::command]
pub async fn list_models(state: State<'_, AppState>) -> Result<Vec<ModelInfo>> {
    let (client, base_url) = (state.http.clone(), state.base_url());
    ollama::list_models(&client, &base_url).await
}

#[tauri::command]
pub async fn running_models(state: State<'_, AppState>) -> Result<Vec<RunningModel>> {
    let (client, base_url) = (state.http.clone(), state.base_url());
    ollama::running_models(&client, &base_url).await
}

/// Immediately evict a model from VRAM. The highest-leverage quiet-mode action.
#[tauri::command]
pub async fn unload_model(state: State<'_, AppState>, model: String) -> Result<()> {
    let (client, base_url) = (state.http.clone(), state.base_url());
    ollama::unload(&client, &base_url, &model).await
}

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn get_telemetry(state: State<'_, AppState>) -> TelemetrySample {
    match lock(&state.last_sample).clone() {
        Some(sample) => sample,
        None => state.sample_now(),
    }
}

#[tauri::command]
pub async fn sample_telemetry(state: State<'_, AppState>) -> Result<TelemetrySample> {
    Ok(state.sample_now())
}

// ---------------------------------------------------------------------------
// Chat streaming
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct StartChatRequest {
    /// Generated by the frontend so it can correlate events from the first token.
    pub stream_id: String,
    pub model: String,
    pub messages: Vec<ChatMessage>,
    #[serde(default)]
    pub options: Option<Value>,
    #[serde(default)]
    pub keep_alive: Option<Value>,
    #[serde(default)]
    pub tools: Option<Value>,
}

#[derive(Debug, Clone, Serialize)]
struct ChunkPayload {
    stream_id: String,
    content: String,
}

#[derive(Debug, Clone, Serialize)]
struct ToolPayload {
    stream_id: String,
    tool_calls: Value,
}

#[derive(Debug, Clone, Serialize)]
struct DonePayload {
    stream_id: String,
    cancelled: bool,
    stats: ChatStats,
}

#[derive(Debug, Clone, Serialize)]
struct ErrorPayload {
    stream_id: String,
    message: String,
}

/// Stream a chat completion, emitting `hush://chat/*` events as it runs.
///
/// No lock is held across an `.await`, which keeps the future `Send`; the
/// cancellation flag is checked between NDJSON lines, which is what makes the
/// Stop button feel instant.
#[tauri::command]
pub async fn start_chat(
    app: AppHandle,
    state: State<'_, AppState>,
    request: StartChatRequest,
) -> Result<()> {
    let client = state.http.clone();
    let base_url = state.base_url();

    let cancel = Arc::new(AtomicBool::new(false));
    lock(&state.streams).insert(request.stream_id.clone(), cancel.clone());

    let body = ollama::chat_body(
        &request.model,
        &request.messages,
        request.options.clone(),
        request.keep_alive.clone(),
        request.tools.clone(),
    );

    let response = match client
        .post(format!("{base_url}/api/chat"))
        .json(&body)
        .send()
        .await
    {
        Ok(response) => response,
        Err(err) => {
            lock(&state.streams).remove(&request.stream_id);
            let message = format!("could not reach Ollama at {base_url}: {err}");
            let _ = app.emit(
                EVENT_CHAT_ERROR,
                ErrorPayload {
                    stream_id: request.stream_id.clone(),
                    message,
                },
            );
            return Err(HushError::Unreachable(base_url));
        }
    };

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        lock(&state.streams).remove(&request.stream_id);
        let message = format!("{}: {}", status.as_u16(), text.trim());
        let _ = app.emit(
            EVENT_CHAT_ERROR,
            ErrorPayload {
                stream_id: request.stream_id.clone(),
                message: message.clone(),
            },
        );
        return Err(HushError::Ollama(message));
    }

    let mut stream = response.bytes_stream();
    let mut buffer: Vec<u8> = Vec::new();
    let mut stats = ChatStats::default();

    while let Some(item) = stream.next().await {
        if cancel.load(Ordering::Relaxed) {
            break;
        }

        let bytes = match item {
            Ok(bytes) => bytes,
            Err(err) => {
                let _ = app.emit(
                    EVENT_CHAT_ERROR,
                    ErrorPayload {
                        stream_id: request.stream_id.clone(),
                        message: format!("stream error: {err}"),
                    },
                );
                break;
            }
        };

        buffer.extend_from_slice(&bytes);

        // Emit one event per complete NDJSON line.
        while let Some(index) = buffer.iter().position(|&b| b == b'\n') {
            let line: Vec<u8> = buffer.drain(..=index).collect();
            let line = String::from_utf8_lossy(&line[..line.len().saturating_sub(1)]);
            let line = line.trim();
            if line.is_empty() {
                continue;
            }

            match serde_json::from_str::<ChatChunk>(line) {
                Ok(chunk) => {
                    if let Some(message) = chunk.message.as_ref() {
                        if !message.content.is_empty() {
                            let _ = app.emit(
                                EVENT_CHAT_CHUNK,
                                ChunkPayload {
                                    stream_id: request.stream_id.clone(),
                                    content: message.content.clone(),
                                },
                            );
                        }
                        if let Some(tool_calls) = message.tool_calls.as_ref() {
                            if !tool_calls.is_empty() {
                                let _ = app.emit(
                                    EVENT_CHAT_TOOL,
                                    ToolPayload {
                                        stream_id: request.stream_id.clone(),
                                        tool_calls: json!(tool_calls),
                                    },
                                );
                            }
                        }
                    }
                    if chunk.done {
                        stats = chunk.into_stats();
                    }
                }
                Err(err) => {
                    let _ = app.emit(
                        EVENT_CHAT_ERROR,
                        ErrorPayload {
                            stream_id: request.stream_id.clone(),
                            message: format!("could not parse Ollama response: {err}"),
                        },
                    );
                }
            }
        }
    }

    lock(&state.streams).remove(&request.stream_id);

    let _ = app.emit(
        EVENT_CHAT_DONE,
        DonePayload {
            stream_id: request.stream_id.clone(),
            cancelled: cancel.load(Ordering::Relaxed),
            stats,
        },
    );

    Ok(())
}

#[tauri::command]
pub fn cancel_chat(state: State<'_, AppState>, stream_id: String) -> bool {
    match lock(&state.streams).get(&stream_id) {
        Some(flag) => {
            flag.store(true, Ordering::Relaxed);
            true
        }
        None => false,
    }
}
