# What the people in a callout say when the player talks to them.
#
#   <id> = 'first line | second line | third line | ...'
#
# Read by tools\make-callout-library.ps1, which attaches the lines to the recipe with that id and writes
# them into the recipe's <Script>. TextDispatch asks for these before its own scripted replies and before
# the language model, so a suspect in a callout answers in character, in order, with no model involved -
# see src\TextDispatch\Bridges\CalloutScriptBridge.cs. The last line repeats, because somebody who has
# said their piece three times is still better company than somebody who has gone mute.
#
# A data file rather than code: Import-PowerShellDataFile parses it as data, so nothing in here can run.
# Written in plain single-quoted strings, which is why an apostrophe must be doubled - and why the
# generator refuses a line that has one, since a line that breaks the file is a library that will not
# build at all.
#
# The generator also refuses to write a library where any callout has fewer than three lines, or where a
# key here does not match a callout id: "every callout has a script" is checked, not hoped for.
#
# Who speaks: the first suspect in the scene, or the patient in a medical callout, or whoever is standing
# there if the callout has neither. One speaker per scene - a scene with two conversations in it is two
# callouts. So these lines are written in the voice of that person, and lines 1 to 3 read as a sequence:
# what they say first, what they say when pressed, and the turn.

@{

# ============================================================ The two that any agency can be sent to
'all-assault-on-officer' = 'I never touched him. Ask the man in the van, he pulled me off. | You are hurting my arm. It was already like that before you got here. | He went for me first. That is the whole of it. That is what happened.'
'all-officer-needs-assistance' = 'We had nothing to do with that. We were walking home. | Do not come closer. I am telling you, do not come closer. | You are not taking me in. I am not going back there.'

# ============================================================ The deep ones: a scene that talks back
'deep-hostage-standoff' = 'I have not done anything. I am not coming out for you. | You are not listening to me. None of you ever listen. | If I come out, what happens? Tell me what happens. | Alright. Alright. I am putting my hands on my head.'
'deep-bank-siege' = 'We are not opening the door. | Nobody has been hurt. We do not want anybody hurt. | We want a way out of here and we want it in writing. | We are sending somebody out. Do not shoot.'
'deep-medical-patient-talks' = 'Do not move me yet. Not until I have said this. | I take tablets. The blue ones, twice a day. I have not had them since Thursday. | I feel like I am going to be sick. | Thank you. I am ready now.'
'deep-gang-fight' = 'He started it. He started it outside the shop. | You are not taking me anywhere. I have not done anything. | My cousin is coming. You want to be gone when he gets here.'

# ============================================================ Medical
'ems-allergic-reaction' = 'It was in the sauce. I asked them twice and they said there were no nuts in it. | My throat is closing. This is not a cold, I know what this is. | I have a pen for it. It is in my bag. Right hand pocket.'
'ems-anaphylaxis-child' = 'It is my son. He is four years old and he ate it at the table. | I did not know there was any in it. I would never have given him any. | I used the pen. It is the small one, the one they give you for children.'
'ems-assault-victim' = 'Two of them. It came out of nowhere. | I did not get a proper look. Baseball cap, dark jacket, that is all. | Which way did they go? Tell me which way they went.'
'ems-birth' = 'It started on the way here and it has not stopped since. | Two minutes apart. I have been counting them. | I am not going anywhere. This is happening now, in this room.'
'ems-broken-ankle' = 'It has been like this for an hour. I have not moved an inch. | I heard it go. There is no way I am walking down on it. | How are you getting me off this hill? Do not say by stretcher, because that is a joke.'
'ems-burn-injury' = 'It was the pan. It came off the stove and straight over my arm. | Somebody put cold water on it and then somebody else said not to. | It is the fingers. That is the part that will not stop.'
'ems-burns-face' = 'The gas ring. It caught the moment I went to light it. | I turned away, but I was not quick enough. | Just tell me it is not my eyes. Somebody tell me it is not my eyes.'
'ems-carbon-monoxide' = 'It is the boiler. It has been making that noise for weeks. | We all went sleepy, one after the other. All of us. | The children are outside. I put them outside before I called you.'
'ems-chemical-inhalation' = 'One breath. One breath and it went straight into my chest. | Nobody told us what was in the drum. Nobody knows what was in the drum. | I am not going back in there. Do not ask me to go back in there.'
'ems-chest-pain' = 'It came on in the street. I sat down on the first bench I could find. | I have had one before. This is not that one. It is different. | Do not let me walk to the ambulance. I know what walking does.'
'ems-child-drowning' = 'She was under for a while. I do not know how long. | I pulled her out myself and I did the breaths, the ones they show you. | She coughed. That was the sound I wanted. That was the sound.'
'ems-choking' = 'It was a piece of steak. It went down the wrong way. | I put my hands up and somebody did the thing. Somebody did it properly. | I have never been that frightened. That is not an exaggeration.'
'ems-cyclist-down' = 'The door opened in front of me. I had nowhere left to go. | My wrist went under me, but the arm is the problem, not the wrist. | Nobody got the number. Do not ask me for the number.'
'ems-dehydration' = 'It was a half marathon. I have done the distance plenty of times. | I stopped sweating about four miles back. That is when it went wrong. | Water. Not a bottle. All of it.'
'ems-diabetic' = 'I have not eaten since yesterday. It slipped my mind completely. | My hands are shaking and I cannot get a thought to stay still. | Sugar. Anything with sugar in it. Orange juice if anybody has one.'
'ems-dialysis-missed' = 'The transport did not come. It did not come and I could not get there on my own. | I can barely stand up. My legs are like paper. | Do not touch this arm. That is the fistula. Do not touch this arm.'
'ems-dog-bite' = 'It was off the lead. It came from behind the gate. | The owner called it off and then just walked away. She said it had never done that. | It is the bleeding I cannot stop looking at.'
'ems-domestic-injury' = 'It is the door. I walked into the door. | He has gone. He took the car and he has gone. | If you write it down, he will see it written down. Do you understand what I am saying?'
'ems-drowning' = 'The current took me sideways. I could not get back in. | Somebody went in after me. I want to know who it was. | I saw the light on the water and then I saw nothing for a while.'
'ems-elderly-confusion' = 'I was looking for the bus. I know this street. I do not know this street. | Something has not been right all evening. | Is it Wednesday? It cannot be Wednesday.'
'ems-electric-shock' = 'The breaker was supposed to be locked off. It was not locked off. | It threw me back about six feet. I remember the bang. | My hand will not stop. It is still going through me.'
'ems-exposure' = 'The fog came down and the path went with it. | I sat behind a wall for a while. That made it worse, not better. | I cannot get warm. I have been shaking for an hour and I cannot get warm.'
'ems-fall-elderly' = 'I went down in the hallway and I have been here since. | The key is under the plant pot. The neighbour will show you. | Do not lift me by the arms. Please do not lift me by the arms.'
'ems-fall-from-height' = 'Third rung. It was not even the top of the ladder. | I had a box of tiles in one hand. That is why I went. | It is my back. Everything else is fine, it is my back.'
'ems-farm-machinery' = 'It was the power take-off. It caught the sleeve and it pulled. | Do not touch the tractor. It is still in gear. | Nobody switches it off except me. That is the rule on this farm.'
'ems-food-poisoning' = 'It is the buffet. Everybody who had the buffet is like this. | Nine of them now. Three went home before we thought to call you. | It is still out on the table. Nobody has touched it since.'
'ems-forklift' = 'He came round the corner and I had nowhere to step. | It was slow. That is the part people will not believe, it was slow. | Do not tell me what it looked like. I do not want to know what it looked like.'
'ems-glass-assault' = 'It was a glass. He used a glass. | It was the neck, they said. They said it went in at the neck. | I am holding it because that is all I can do.'
'ems-gunshot-wound' = 'It came from the car. I did not see a face. | I felt it before I heard it. That is the strange part. | Is there a lot of blood? Do not lie to me about the blood.'
'ems-head-injury' = 'I do not remember anything after the kerb. | Somebody said I was out for a minute. I do not believe them. | I keep wanting to go to sleep. Tell me I can go to sleep.'
'ems-heat-exhaustion' = 'I have been out in it since the morning. No shade, no water. | I stopped feeling hot a while ago. Now I am cold, which makes no sense. | I am not going to hospital. I just need to sit for a minute.'
'ems-industrial-accident' = 'The guard came off the machine. It should never have been off. | I have been on that line eleven years. Nothing has ever done that. | The foreman is not here. Nobody knows where the foreman is.'
'ems-machinery-shear' = 'It came down on the sleeve and then it was my arm. | It is holding me. I can feel it holding me. | Talk to me. Just keep talking to me.'
'ems-multiple-shooting' = 'We were both outside. It all happened at once. | I got down behind the car. He did not get down in time. | Do not leave him. Whatever else you do, do not leave him.'
'ems-multiple-stabbing' = 'It was three of them and it was quick. | My friend is by the bins. He is worse off than me. | I cannot stand up. Every time I try, it goes.'
'ems-overdose-park' = 'It was meant to be the same as always. It was not the same. | Nobody gave it to me. I am not saying who did. | There is no name on it, is there. There is never a name on it.'
'ems-overdose-teen' = 'It is my friend. She took something at the party. | I do not know what it was. Nobody at that party knows what it was. | Is she awake? Just tell me if she is awake.'
'ems-pedestrian-struck' = 'I was on the crossing. I am sure I was on the crossing. | It came from the left. I only heard it. | Somebody has my bag. My bag is over by the wall.'
'ems-psychiatric' = 'I do not need an ambulance. I am not the one who called. | My brother is inside and he has not come out of that room in three days. | He is not a danger to anybody. He is frightened, that is all.'
'ems-punch-injury' = 'One punch. That is all it was, one punch. | He walked off towards the taxi rank. | My teeth feel loose. Is that normal, teeth feeling loose?'
'ems-respiratory' = 'It came on in the night. I have been sat up since four. | The blue inhaler is finished and the other one makes my heart race. | If I lean forward it is easier. Let me lean forward.'
'ems-seizure' = 'It has happened before. Not like this, but it has happened. | I bit my tongue. I can taste it. | Everybody is staring at me. Can you move them back?'
'ems-sepsis' = 'It started as a chest thing last week. | I have been shaking since the morning and I cannot keep anything down. | Is it the infection? Tell me straight, is it the infection?'
'ems-sport-head' = 'I went up for the ball and I do not remember landing. | How long was I out? Nobody will tell me how long. | I want to go back on. I know what you are going to say.'
'ems-sports-injury' = 'It was the tackle. Studs up, right on the shin. | I heard it crack before I felt anything. | Do not let them carry me off. I can hop, I have done it before.'
'ems-stab-wound' = 'Outside the takeaway. It took two seconds. | I have a jacket over it. Somebody told me to hold the jacket. | Is that much blood normal? Somebody answer me.'
'ems-stairs-fall' = 'I missed the last step with a full basket in my arms. | I went down the whole flight. I remember all of it. | It is my back and my wrist. The wrist took the landing.'
'ems-stroke' = 'It came on while I was on the phone. The words just went. | My face feels wrong on this side. I can feel it drooping. | What time is it? Somebody write down what time it is.'
'ems-withdrawal' = 'Third day. It is always the third day. | I am not going to hospital. They will only do the same thing again. | I have done it before. I can do it again. I just need to get through tonight.'

# ============================================================ Fire
'fire-alley-rubbish' = 'It is not ours. It was going before we opened up. | It has come up through the boards and it is under the fence now. | There is a gas main along that wall. That is why we called you straight away.'
'fire-boat' = 'It went up at the stern. I smelled it before I saw it. | There is fuel aboard. Two hundred litres of it. | It is not my boat. I am watching it for somebody.'
'fire-caravan' = 'It started inside. Nobody was in it, thank God. | There is a gas bottle under the sink. The big one. | We are all out of ours, but there are four more down that row.'
'fire-car-row' = 'One went up and then it was two, and then it was all of them. | They are parked nose to tail. That is the whole problem. | People are still trying to drive out. Somebody needs to stop them.'
'fire-chimney' = 'It is in the chimney. It has been going since the fire was lit. | The sweep was booked for next month. That is the truth of it. | I have not put water on it. Somebody told me not to.'
'fire-commercial-bins' = 'It is the bins round the back. It has been smouldering all night. | It has taken the fence, and the fence goes to the yard. | The yard is full of pallets. Hundreds of them.'
'fire-electrical-depot' = 'We killed the power at the main. Everybody is out and counted. | It is the cabinet by the loading bay. It has been arcing for a week. | Nobody goes near that bay. I have made sure of that.'
'fire-factory' = 'Everybody is out. We counted them at the gate. | It is in the paint store. That is the one that frightens me. | There is a man unaccounted for. He was on the mezzanine.'
'fire-flat-smoke' = 'The smoke is in the stairwell and it is going up. | Nobody has come past me and I have been here ten minutes. | The door of number six is warm. I am not touching it.'
'fire-garage' = 'There is a motorbike in there and a can of petrol beside it. | It is attached to the house. That is what I am worried about. | I opened the door and it went up in my face. That is why my eyebrows have gone.'
'fire-gas-leak' = 'I can smell it from here. It has been all morning. | The engineers are not coming until tomorrow. I have it in writing. | It is strongest outside number eleven. That is where I would start.'
'fire-grass-fire' = 'It started at the path and the wind has it now. | There are houses behind the ridge. They will not see it until it is on them. | Two of us have been beating it with coats. It is doing nothing.'
'fire-grass-hills' = 'It is going up the hill rather than across. That is something. | If the wind turns it comes down onto the gardens. | Everybody on the top road has been told to leave. Not all of them have.'
'fire-house-occupied' = 'There is somebody in the back bedroom. My brother is in the back bedroom. | I could not get up the stairs. The smoke beat me back. | He is deaf. You need to know that before you go in, he is deaf.'
'fire-kitchen-fire' = 'It was the chip pan. It went up the moment I put water near it. | Everybody is out. All four of us. | The flat door is open. I left it open so you could get in.'
'fire-refuse-fire' = 'The bins went up behind the row of shops. | There is a takeaway extractor on that wall and it is full of grease. | It has been going twenty minutes and nobody has come out.'
'fire-restaurant' = 'It is the kitchen. Everybody is out the front. | There is a gas line in there and a fryer right beside it. | The chef has burnt his arm. He is sat on the kerb.'
'fire-vehicle-car-park' = 'I was two cars away when it went up. | I have been coughing since. My chest feels tight. | I am not leaving until I know about my car. Just tell me about my car.'
'fire-vehicle-roadside' = 'It went up while I was driving it. I got out at the lights. | It runs on gas. There is a tank in the back of it. | I am insured. Just tell me what to do and I will do it.'
'fire-warehouse' = 'We do not know what is in there. It is pallet racking, all of it. | The last delivery was aerosols. That is all I can tell you. | The shutter is shut and it is hot to the touch. Do not open the shutter.'

# ============================================================ Prison
'saspa-assault-on-staff' = 'He came at me the moment I opened the hatch. Nothing led up to it. | He is restrained and he is not injured. I am the one bleeding. | I want this recorded. I want all of it recorded properly.'
'saspa-contraband-drop' = 'It came over on the hour. Same spot as last week. | It was wrapped in tape and there was a phone inside it. | There is a vehicle comes past slowly most nights. That is all I have.'
'saspa-drone-drop' = 'It came in low over the yard and dropped it by the workshop. | Two of them, one flying and one watching. That is what it looked like. | It was gone before anybody could get near it.'
'saspa-drug-find' = 'It was behind the vent, not on him. | Three of them share that cell and not one of them is talking. | There is more of it somewhere. There always is.'
'saspa-escape-grounds' = 'One missing at roll call and the gate has not been touched. | He is not on the yard and he is not in the block. That leaves the grounds. | He has been talking about the wall for a fortnight. Everybody heard him.'
'saspa-escape-vehicle' = 'A car came up to the perimeter road and it did not stop. | Somebody came over the wall and got straight into it. | I have half the plate. Do not ask me for the rest of it.'
'saspa-medical-emergency' = 'I came over dizzy in the workshop. It came on out of nowhere. | I have not felt right since breakfast. Nobody else has been ill. | Do not take me to the wing. Anything but the wing.'
'saspa-perimeter-alarm' = 'The alarm went on the north fence and there is nothing on camera. | That camera has been offline two days. I have logged it twice. | I am not sending anybody out there on their own.'
'saspa-self-harm' = 'He has been assessed and he is on fifteen minute checks. | He has not said a word since yesterday, and that is not like him. | I am asking properly. I am asking you to come and see him.'
'saspa-transfer-escort' = 'Court in the morning. It has to be a two unit escort. | He has been violent twice this month. Both times in the van. | If it is one unit I am not moving him. That is the end of it.'
'saspa-transport-incident' = 'He will not get out of the van. He has been sat there twenty minutes. | He is cuffed and he is going nowhere, but then neither are we. | Two of us and one of him, and we both want to go home tonight.'
'saspa-visitor-argument' = 'It is two families in the visitors hall and it is getting loud. | Nobody has thrown anything yet. That is the bit I would watch. | We are pulling the visit now, before it gets any worse.'
'saspa-visitor-contraband' = 'It was in the pram, under the blanket. | She says she did not know it was in there. They all say that. | It is bagged and it is in the office. Do not touch it without gloves.'
'saspa-yard-fight' = 'Two of them in the yard and about twenty watching. | It is over a debt. It is always over a debt. | We need them apart before the watchers decide to join in.'

# ============================================================ The set pieces
'story-armoured-truck' = 'The crew are not answering the radio and the engine is still running. | There are two in the front and I have not seen either of them move. | The back door has been worked on. I can see the marks from here.'
'story-bank-heist-aftermath' = 'They came out of the back and went on foot through the car park. | Two of them and they are carrying. Take that seriously. | One of them is limping. He went down on the steps and he is limping now.'
'story-hood-safari' = 'They are shooting at anything that moves out here. Anything. | That is the third volley in ten minutes. It is coming from the trees. | I am not going back for my truck. Leave the truck.'
'story-jewel-store-job' = 'They put a brick through the window and took the tray. | Two minutes. That is all it took, two minutes. | They went across the road into the alley. Both of them.'

# ============================================================ The other packs, by name
'uc-armed-clown' = 'It is a mask. It is only a mask. The weapon is real enough though. | He has been stood there an hour and nobody will go near him. | He was asking people for money. That is why the first call came in.'
'uc-atm-activity' = 'Two of them, and they have been at that machine since the bank shut. | One has a bag of tools and the other one is watching the road. | They are drilling it. You can hear it from the bus stop.'
'uc-cyclist-motorway' = 'I am allowed to be here. I have as much right as you do. | The drivers are the ones in the wrong, not me. | I am not getting in the back of a car. I will ride off at the next junction.'
'uc-gang-shootout' = 'I was nowhere near it. I came out when I heard the shots. | It is two families and it has been building all week. | You want to look at the blue car. Everything comes back to the blue car.'
'uc-k9-backup' = 'He went through the fence and into the field. That way. | I kept eyes on him as far as the fence and then I lost him. | He is not armed as far as I know. I am not certain of that.'
'uc-metro-disturbance' = 'It is one man and he is walking the platform shouting at people. | Staff have stopped the trains on this side. That is why everybody is stuck. | He has a bag and he will not put the bag down.'
'uc-money-truck-theft' = 'They have the crew locked in the back of the truck. | Three of them, and they came in a van with no plates. | They are still at it. They have not gone yet.'
'uc-person-with-knife' = 'He is not doing anything. He is just stood there with it. | Everybody has backed up to the shop front. That is the whole crowd. | He said something about his brother. Nobody understood it.'
'uc-stolen-bus' = 'It came off the depot with no lights and it has not stopped since. | The driver is one of ours and he is not answering the radio. | It cannot get far in a bus. It cannot get far and it cannot hide.'
'uc-stolen-commercial-vehicle' = 'It went off the yard at about four this morning. | There is a tracked digger on the back of it. That is the part that worries me. | The keys were in the office. They are always in the office.'
'uc-stolen-emergency-vehicle' = 'It was taken from outside the department with the keys left in it. | It has a full tank and a radio. That is the problem. | Whoever has it can hear everything we say.'
'uc-warrant-for-arrest' = 'He is in there. I saw him at the window half an hour ago. | He does not come out in the day. Only at night. | There is a dog. I am telling you now, there is a dog.'

# ============================================================ Los Santos Police
'lspd-abandoned-call' = 'I did not mean to call you. It went off in my pocket. | There is nothing wrong here. Look at me, there is nothing wrong. | I am sorry. I will not waste your time again.'
'lspd-aggressive-begging' = 'I am not begging. I am asking. There is a difference. | I have been outside this bank two hours and not one person has stopped. | You want me moved on. Moved on to where, exactly?'
'lspd-aggressive-dog' = 'He is not dangerous. He has never done that before. | It is hats. He goes for people in hats and I do not know why. | I have got the lead. Whatever you do, do not run.'
'lspd-armed-robbery-off-licence' = 'I have not touched the till. Ask them, I have not touched it. | The gun is not real. Look at it, it is not real. | I came in for cigarettes. That is the whole of it.'
'lspd-armed-robbery-pharmacy' = 'They made me do it. I am not going to say who. | Nobody in here is hurt. Nobody has been hurt. | I am putting it on the counter. Look, I am putting it down.'
'lspd-armed-standoff' = 'I am not putting it down until you back off. | I told you what I want and you were not listening. | You have got all night. So have I.'
'lspd-assault-in-progress' = 'He put his hands on me first. That is why it happened. | Nobody called you. This is between us. | I am done. Look at me, I am done.'
'lspd-bag-snatch' = 'It was on the bench next to her. I thought it had been left there. | I have not run anywhere. I am stood right here. | You want it back? Here. Take it.'
'lspd-bail-check' = 'I have not been near that address. Check the tag. | You can see the tag on my ankle. It has not gone off once. | This is harassment. That is what this is.'
'lspd-bank-robbery' = 'We are not opening anything. Not for you. | Nobody has to get hurt here. Nobody is hurt yet. | The safe has a timer on it. You can wait as long as you like.'
'lspd-bar-fight' = 'He started it inside and he brought it out here. | I have had four pints. That is not a crime. | My nose is broken. So who is the victim here?'
'lspd-beach-disorder' = 'It is a beach. People are allowed a drink on a beach. | Nobody is fighting. Nobody is even shouting. | You want us gone, we are gone. Just leave my mates alone.'
'lspd-bike-theft-crew' = 'I sell bikes. Buying and selling, that is all this is. | The croppers are for the lock. They are not for anything else. | Nothing here is stolen. Not one of them. Check the frames.'
'lspd-burglary' = 'The window was already open. I was checking nobody was hurt inside. | I have not taken a thing. Feel my pockets, go on. | It is my aunt who lives here. She is away, that is why it is empty.'
'lspd-bus-assault' = 'He put his bag on my legs. That is how it started. | Ask the driver. The driver saw all of it. | I want him arrested as well. Both of us, that is fair.'
'lspd-car-alarm' = 'It is not my car. I am waiting for whoever owns it. | It has been going since last night and it is not my car. | I have called about it twice. Nobody has come.'
'lspd-car-break-in' = 'It is my car. The window is mine and the car is mine. | I locked the keys inside it. That is why the window is out. | Look at the registration. Go on, look at the registration.'
'lspd-carjacking' = 'The engine was running and the door was open. I got in. | I did not pull anybody out of anything. Ask him. | It is a mistake. A stupid mistake.'
'lspd-car-meet' = 'I am parked. Everybody here is parked. | Nobody is racing. We are stood around talking. | It is a car park. That is what a car park is for.'
'lspd-cash-in-transit' = 'It was two of them on a bike. I was on the ground. | They took the box and went north. I did not get a look. | One of them had a shotgun. You need to know that.'
'lspd-cash-machine-damage' = 'It was like that when I walked past. | I am waiting for a taxi. That is why I am stood here. | Check my hands. Go on, there is no dye on my hands.'
'lspd-catalytic-theft' = 'I am not cutting anything. I am looking, that is all. | It is my van. Mine. That is why I am under it. | The saw is for work. I am a builder.'
'lspd-charity-theft' = 'I put money in that tin. I did not take money out of it. | It was on the counter and nobody was watching it. | I have a receipt from the shop next door. Look at the time on it.'
'lspd-child-neglect' = 'They are asleep upstairs. I look in on them every hour. | I went out for twenty minutes. Twenty minutes, that is all. | Their mother is coming back tonight. She is on a late shift.'
'lspd-copper-theft' = 'It is scrap. Scrap is legal. | I did not go near the live side. I know what I am doing. | The cable was already down. It was on the ground when I got here.'
'lspd-counterfeit-currency' = 'That is the note they gave me in the change. I am not the one making them. | The machine took it. Why would I hand over a note the machine takes? | Check the wallet. If there are more of them in there, charge me.'
'lspd-curfew' = 'I am fifteen minutes late. That is nothing. | I missed the bus. That is the only reason I am out. | My mum is at the corner waiting. Ask her.'
'lspd-dealing-crew' = 'We are not selling anything. We are stood here. | It is a public corner. Anybody can stand on a corner. | You have got nothing on me and you know it.'
'lspd-dine-and-dash' = 'The food was cold when it came. That is why we stopped paying. | We would have paid. We were going to pay. | I have got money on me. Look, I have got money on me.'
'lspd-drive-by' = 'It came past, there were shots, and then it was gone. | I did not see the plate. Nobody saw the plate. | There is a boy on the pavement. Somebody needs to help him.'
'lspd-drone-over-prison' = 'I am flying it over the field. The field is public. | You can look at the footage. There is nothing on the footage. | I can bring it down. Just tell me to bring it down.'
'lspd-drug-deal' = 'I was buying. Buying is not dealing. | It is a small amount. Look at it, it is a small amount. | I am not saying where I got it. I am not saying that.'
'lspd-drug-house' = 'It is a shared house. People come and go from a shared house. | I rent a room. I do not know what the others get up to. | You need a warrant for the rest of it, and I know my rights on that.'
'lspd-drunk-disorderly' = 'I am not drunk. I have had a few. I am not drunk. | They threw me out and I have been stood here since. | I am going home. Just let me go home.'
'lspd-elder-abuse' = 'She bruises easily. She is eighty-nine, everybody bruises her. | I have looked after her four years and nobody has complained before. | Ask her yourself. She will tell you.'
'lspd-false-alarm' = 'It was me. I have the code. Look, I have the code. | That alarm does this. It does it when the wind is up. | I have been here twenty minutes. The keyholder is on his way.'
'lspd-fare-dispute' = 'Nine dollars to here. That is not the price it should be. | I am not paying a figure that was not on the metre. | I have the money. It is the amount I am arguing about.'
'lspd-fight-in-street' = 'It is between the two of us. It has nothing to do with you. | He has got a bottle. Look at his hand, he has got a bottle. | Everybody here will tell you the same thing.'
'lspd-fireworks' = 'They are fireworks. It is a birthday. | We are doing it in the street because the garden is too small. | There is one left. I will put it down, look, I am putting it down.'
'lspd-foot-pursuit-backup' = 'He went through the gardens and I am not going over that fence on my own. | He is in the back of those houses. I have not lost him. | Two of us and a cordon. That is what this needs.'
'lspd-found-property' = 'I found it on the bench outside. Everything was still in it when I looked. | I did not take anything out of it. I looked and I put it back. | There is a card in it with a name on. That is why I brought it in.'
'lspd-found-weapon' = 'I found the knife in the garden. It was in the flowerbed. | I brought it in because of the children. There are children next door. | I have not touched the blade. I picked it up by the handle.'
'lspd-fraud-report' = 'It came off the account this morning. Two thousand. | I have the printout here, and the transaction number on it. | I have never been to that shop. Never in my life.'
'lspd-fuel-driveoff' = 'The pump would not take my card. I was going to come back. | I live ten minutes from here. Ask anybody. | I will pay it now. I will pay it now, in cash.'
'lspd-gang-intimidation' = 'Nobody is intimidating anybody. We are delivering a message. | He owes money to people and that is his problem. | You can stand there all day. It does not change anything.'
'lspd-garage-burglary' = 'The side door was open. I was looking to see what had been taken. | The bikes are mine. All three of them are mine. | Check the frames. There are numbers on the frames.'
'lspd-graffiti' = 'It is a wall. It is a blank wall and it has been blank for years. | I am not damaging anything. I am putting something on it. | Cans are legal. You can buy cans in any shop.'
'lspd-grow-house' = 'It is a rented house. I do not know who is in it. | I am the landlord. I have not been inside in a year. | There is a smell, yes. I have reported the smell myself.'
'lspd-hospital-disturbance' = 'I have been waiting four hours and nobody has told me anything. | My father is in there and they will not let me see him. | I have not threatened anybody. Ask the staff.'
'lspd-hotel-disturbance' = 'They put us in a room next to theirs. That is the whole problem. | Nobody has thrown a punch. It was shouting, that is all. | I am going back to my room. I am not staying in this corridor.'
'lspd-illegal-firearm-sale' = 'It is a part. It is a spare part for a hobby. | I am selling it to him because he asked for one. | There is no ammunition. Look, there is no ammunition.'
'lspd-illegal-parked-taxi' = 'I have been on this rank nine years. This is my spot. | He is the one who pulled in on top of me. | I am not moving until somebody tells me who was first.'
'lspd-illegal-vendor' = 'I have a licence. It is at home in a drawer. | I am not blocking anybody. There is a path behind me. | Everybody in this market is doing the same thing.'
'lspd-indecent-exposure' = 'I was changing. Nobody was supposed to be looking. | I have got a bag right here with my clothes in it. | I am not doing anything. I am sat on a bench.'
'lspd-man-with-a-gun' = 'It is in my waistband because I am allowed to carry it. | I have got a permit. It is at the house. | Nobody has been threatened. Ask anybody here.'
'lspd-meth-lab' = 'I rent it out. I have never been inside it. | The smell is the drains. It has been the drains for a year. | Ask the tenants. Oh wait, you cannot, because they have gone.'
'lspd-missing-child' = 'He was with me on the escalator and then he was not. | Two minutes. I looked down at my phone for two minutes. | He is seven. He has a red jacket on. That is all I can tell you.'
'lspd-missing-person' = 'He walked out this morning and he has not come back. | He does not carry a phone. He never has. | That is his picture. That is the best one I have got.'
'lspd-mugging' = 'Two of them. One in front and one behind. | They took the phone and the watch. That is all they took. | I am not hurt. I am shaken up, I am not hurt.'
'lspd-museum-vandalism' = 'I put my hand on the case. That is all I did. | The case was cracked before I got there. | Ask the staff. There is a camera pointing right at it.'
'lspd-nightclub-ejection' = 'I paid to get in and I am not leaving. | The bouncer put his hands on me first. | One drink. I have had one drink and they threw me out.'
'lspd-noise-complaint' = 'It is a Saturday night. It is music, not a crime. | The neighbours have complained five times and it is always them. | I will turn it down. Look, I am turning it down.'
'lspd-obstruction' = 'I am loading. The van is here and I am loading it. | Five minutes. I have been here five minutes. | Where am I supposed to park? There is nowhere to park.'
'lspd-office-burglary' = 'The alarm went off at four and nobody came until now. | The back door was forced. I have not touched the back door. | I am the one who called it in. I am the manager.'
'lspd-parcel-theft' = 'It had my name on it. That is why I picked it up. | I am delivering, not taking. Look at the van. | There are six more on the step. Take a look at all of them.'
'lspd-pawn-shop' = 'I bought it off a man in a car park. I did not know where it came from. | It is a camera. People sell cameras every day. | I will give it back. It is in the window, take it.'
'lspd-person-in-crisis' = 'I do not want to talk to anybody. I want to be left alone. | I have not done anything wrong. I am sat in my own flat. | You are the fourth person today. The fourth.'
'lspd-phone-snatch' = 'It was on the table outside the cafe. I picked it up. | I was going to hand it in. I was walking towards the station. | It is in my pocket. Here. Here it is.'
'lspd-pickpocket' = 'I am not working anybody. I am stood in a crowd. | My hands are in my own pockets. Look at them. | Everybody in that queue has got a bag. It is not me.'
'lspd-pool-hall-fight' = 'He fouled me on the table and then he laughed about it. | The cue is mine. I brought it in with me. | Ask the man behind the bar. He saw all of it.'
'lspd-prowler' = 'I am looking for a house. My friend lives round here somewhere. | I do not know which number. That is why I am trying the handles. | It is a fair thing to do. I am not breaking anything.'
'lspd-public-intoxication' = 'I am asleep. I was not bothering anybody. | I have got nowhere to go. That is why I am in the doorway. | I will move. Just let me get my things together.'
'lspd-pursuit-backup' = 'They went through the junction on red and kept going. | I am second car. I am asking for a third. | I have got the plate and the direction. That is all I have.'
'lspd-return-domestic' = 'It is the same as last night. It is the same as every night. | Nobody has been hit. Not tonight, not last night. | If you take him away I have got nowhere to go. Do you understand?'
'lspd-rough-sleeper' = 'I am in a doorway because it is minus four outside. | I have not been asked to move by anybody except you. | There is a shelter on the other road. It is full. I checked.'
'lspd-scrapyard' = 'It came in on a truck an hour ago. No paperwork with it. | I have not crushed it. It is still on the pad, look at it. | The man who brought it said he would be back with the papers.'
'lspd-shoplifter-detained' = 'I have got a receipt in my bag for all of it. | The security guard grabbed me before I got to the till. | I am not resisting. Look, I am sat down and I am not resisting.'
'lspd-shoplifting-crew' = 'We are shopping. All four of us are shopping. | The bags are ours. They came in with us. | Nobody has walked out of anything. Nobody has left yet.'
'lspd-shots-fired-residential' = 'It was four or five. It came from the alley. | I put the lights out and got on the floor, like you are told. | I have not been outside. I am not going outside.'
'lspd-shots-into-building' = 'It came through the window while I was sat there. | I am on the floor, I have been on the floor since. | My neighbour has got glass in the front room as well.'
'lspd-shot-spotter' = 'That is the second time tonight on that corner. | The system does not make it up. It picks up the crack. | I have got the log on screen. Four rounds, two shooters.'
'lspd-silent-911' = 'I cannot talk. He is in the next room and he is awake. | The address is right. Just come to the address. | Please do not knock. Please do not knock loud.'
'lspd-stabbing' = 'It was one man and it was fast. | He went towards the park and he was not running. | The other one is on the ground and there is a lot of blood.'
'lspd-stadium-disorder' = 'It is two sets of supporters and it has been going since the whistle. | Nobody has been hurt yet. That is the whole of it, yet. | We need a line down the middle of that street.'
'lspd-stolen-motorbike' = 'It was outside the cafe and I went in for a coffee. | Two minutes. Two minutes and it was gone. | It is black with a red tank. That is all I can tell you.'
'lspd-street-dispute' = 'He has been playing music at three in the morning for a month. | I have complained to the council six times. Six. | Nobody has touched anybody. It is shouting, that is all.'
'lspd-suspicious-drone' = 'It is my drone. I am filming the sunset. | It is over my own garden. Look at the screen, it is my garden. | I will bring it down. It is coming down now.'
'lspd-suspicious-package' = 'It was there at eight this morning and it is still there now. | Nobody has been near it. We cleared the building ourselves. | Do not open it. I am asking you not to open it.'
'lspd-takeaway-robbery' = 'There are two staff locked in the back and they will not come out. | He went out the side door two minutes ago. | He took the till. The till is gone, the staff are not.'
'lspd-taxi-assault' = 'He hit me from the back seat. That is how it happened. | The fare was eleven dollars and he did not want to pay it. | I have got it on the dash camera. It is all on the camera.'
'lspd-theft-in-progress' = 'I was taking it back. That is what I was doing, taking it back. | The bag is full because I had not put it down yet. | I have not left the shop. I am still inside the shop.'
'lspd-threatening-calls' = 'He has called three times today. Same voice, same number. | He says he knows where I live and I believe him. | I want it written down. I want a reference number.'
'lspd-truancy' = 'It is a free period. Everybody in my year has a free period. | I am not even supposed to be in today. | You can ring the school. They will tell you.'
'lspd-unlicensed-cab' = 'I am giving a mate a lift. That is not a taxi. | No money has changed hands. Ask him. | The plate on the roof is for show. It is a joke.'
'lspd-vandalism-school' = 'Twelve windows. It took them twenty minutes. | They came over the field and they were gone before I got round there. | I have got the caretaker key and I am the only one on site.'
'lspd-van-theft' = 'The tools are mine and the van is mine. | I was asleep in the front. That is why I did not answer. | Check the log book. It is in the glovebox.'
'lspd-warehouse-burglary' = 'The shutter has been up about an inch since midnight. | I have watched it on the camera and I am not going in. | There is somebody moving inside. I can see it on the screen.'

# ============================================================ Sheriff, county
'lssd-barn-break-in' = 'The padlock was cut with croppers. That is all I know about it. | Feed and the chainsaw. That is what has gone. | There is a truck comes down this lane most nights. Nobody should be down here.'
'lssd-barn-fire' = 'It went up in the hay. Hay goes fast, everybody knows that. | There is a heifer in the end bay and I cannot get to her. | I have been stood here twenty minutes and it has doubled.'
'lssd-body-in-river' = 'It caught on the branch and I thought it was a coat at first. | I have not been in the water. I have not touched anything. | It has been there a while. That is all I can tell you.'
'lssd-bull-escape' = 'He went through the gate when the post van came up. He hates that van. | He is not vicious. He is a bull, and he is out on a footpath. | If anybody runs, that is when it goes wrong. Tell people not to run.'
'lssd-cattle-on-road' = 'Twenty of them at least. The fence is down at the bottom. | It is a blind bend. Somebody is going to hit one. | We need lights on that road before we do anything else.'
'lssd-county-drink-driver' = 'I have not had anything. I swerved for a deer. | It is my mate who owns the truck. He lent it to me. | I am in the ditch and I am fine. That is the main thing.'
'lssd-desert-body' = 'I was out looking for arrowheads and I found that instead. | It is off the dirt road about two hundred yards. | I have marked it with my jacket. That is all I did.'
'lssd-desert-lab' = 'Generators running all night. You can hear them from the highway. | There is a smell takes the back of your throat off. | Nobody has come out of there. Not once in three days.'
'lssd-diesel-theft' = 'They drilled the tank. That is a proper job, that is not children. | Six hundred litres. That needs a trailer and a pump. | There are tracks running out to the road and they are fresh.'
'lssd-dirt-bikes' = 'Four or five of them, no plates and no helmets. | They go across the field and they are gone before you get near them. | They know these tracks better than anybody round here.'
'lssd-distillery' = 'Copper tubing, drums, and a fire lit under it. | I have smelt that smell for a week and today I went and looked. | Nobody is about, but the fire is lit. So somebody is coming back.'
'lssd-domestic-county' = 'It is the house at the end, with the trailer outside it. | Shouting for an hour and then nothing. That is the part that worries me. | The lights are on and nobody is answering the door.'
'lssd-domestic-firearms' = 'There are guns in that house. I have seen them. | He has not threatened anybody with them, he threatened to use one on himself. | That is why I called. Nobody else was going to.'
'lssd-farmhouse-alarm' = 'It is a monitored alarm and the keyholder is an hour away. | Last time it was a barn door in the wind. This is the house. | I am not going in on my own and there is nobody else out here.'
'lssd-fence-cut' = 'It has been cut with a disc cutter. About forty foot of it. | The stock is on the road and the traffic is not slowing down. | That is twice this month on the same boundary.'
'lssd-firearms-stolen' = 'The cabinet was bolted to the wall and they took the wall with it. | Two shotguns and a rifle. That is what is missing. | I know what that means. I know where they end up.'
'lssd-horse-loose' = 'She got out through the gate somebody left open. | She is a chestnut mare and she is frightened of traffic. | Do not chase her. She will go over the barrier if you chase her.'
'lssd-horse-theft' = 'Her stall was empty this morning and the gate was open. | She is chipped and she is worth real money. That is why they took her. | There are trailer tracks by the gate. They were in and out in ten minutes.'
'lssd-hunter-shot' = 'It came out of the treeline. I did not see a face. | He is on the ground and he is still talking. That is good, is it not? | We are both licensed. Neither of us should be getting shot at.'
'lssd-hunters-trespass' = 'We have permission. The farmer down the road gave us permission. | I am not putting the rifle down until you tell me we can keep it. | Ring him. He is the man in the white house.'
'lssd-illegal-dumping' = 'The van is still there and he is still unloading it. | That is builders waste. Rubble and plasterboard, the lot. | He has been at it twenty minutes with a wheelbarrow.'
'lssd-illegal-logging' = 'Two chainsaws and a flatbed, going since about six. | That is protected woodland. There are markers on every tree in it. | They are loading now. They will be gone inside an hour.'
'lssd-livestock-attack' = 'Nine sheep down and not one of them will stand up. | It was not a dog on its own. Not with that much damage. | Whatever it was is still out there. The dogs are going mad.'
'lssd-livestock-theft' = 'The gate was cut and there are trailer tracks heading out. | Twenty head. That is a big trailer and two people. | They will have gone to the city with them. That is where they go.'
'lssd-missing-hiker' = 'Her car is at the trailhead and she has not come back. | She is fit. She has walked this trail a dozen times. | The weather is turning in tonight, so we are against the light.'
'lssd-moonshine-still' = 'Tubing, drums and a fire under it. Copper tubing. | It is a proper setup up there. It has been going a while. | There is a smell carries down the valley at night.'
'lssd-night-hunting' = 'A lamp, in that field, for the last two hours. | Nobody is looking for anything legal at this hour. | There have been shots as well. Two of them.'
'lssd-poacher-vehicle' = 'It has been there three days. Nobody has come back for it. | The doors are open and the keys are in it. | There is blood in the back. Just so you know what you are walking up to.'
'lssd-poaching' = 'Shots after dark and a truck parked at the treeline. | That is not a target shooter. Not at this hour. | Assume they are armed. That would be my advice.'
'lssd-prisoner-escape' = 'He is still in cuffs. Cuffed in the front. | He crossed the road and went down towards the river. | I am not chasing him on my own across that ground.'
'lssd-quarry-trespass' = 'They are climbing on the plant. That is all it is. | It is a disused site and there is a shaft at the back of it. | If one of them goes down that shaft, this becomes a different call.'
'lssd-ranch-hand-missing' = 'He has not come back from the fence line and that is four hours. | His quad is still in the barn. So he is on foot. | He does not carry a phone and it has never mattered before.'
'lssd-ranch-trespass' = 'He is walking my fence line with a rifle over his shoulder. | Nobody has been threatened. Not yet. | I have been on this land forty years. He is not supposed to be on it.'
'lssd-rural-burglary' = 'The back door was put in and they took the guns and the silver. | We were away three days. That was the window. | Do not touch the back door. I want that photographed properly.'
'lssd-rustling' = 'There is a trailer at the field gate and they are loading it. | At half past two in the morning. That tells you everything. | Two of them, and one is watching the road.'
'lssd-sandy-shores-fight' = 'It is four of them and it has spread out into the street. | They have all known each other twenty years. That does not help. | One is on the ground and I have not seen him move.'
'lssd-shots-at-farm' = 'It came through the kitchen window and I was stood right there. | Two shots. From the field behind the house. | I have got the round. I picked it up off the floor with a cloth.'
'lssd-small-town-robbery' = 'He came in with a can of petrol and a lighter. | He took the cash drawer. Everybody is fine, everybody got out. | He went south on the highway in a red car.'
'lssd-still-fire' = 'It is the outbuilding, and there is a still in it and it is burning. | It has taken the roof and there is a propane tank against the wall. | Nobody is in there. Nobody has been in there tonight.'
'lssd-stolen-quad' = 'It was in the yard last night and this morning the gate was open. | Red, with a winch on the front. It is a working machine. | There are tyre marks running out to the road.'
'lssd-stolen-tractor' = 'You cannot hide a tractor. That is what I do not understand. | It went out of the gate and turned left. That is what the tracks say. | It has a tracker on it. Somebody could find it if they wanted.'
'lssd-stolen-trailer' = 'The hitch was unhitched and the trailer was gone. | It is a livestock trailer. Thirty foot, grey. | That needs a vehicle with a hitch, and nobody saw one.'
'lssd-trail-damage' = 'They have torn the trail up for half a mile. | It is protected ground and they came in the night to do it. | Four sets of tracks. Big tyres, all four of them.'
'lssd-trailer-meth' = 'There is a trailer parked on the verge and nobody in it. | The smell is coming off it. You can smell it from the road. | There is a generator running inside it. That is what I can hear.'
'lssd-wanted-person' = 'I was on the trail and he was coming the other way. | He looked at me and then he turned round and went back. | I have seen the picture. It was him. I am sure of it.'
'lssd-wild-dogs' = 'They have had two of my lambs and my neighbour has lost three. | It is a pack of four at least. They are not frightened of anything. | I would bring a rifle if I were you. I would, honestly.'

# ============================================================ The 686 callouts, by name
'p686-aircraft-in-distress' = 'It came over the trees low and it did not come back up. | I can hear it but I cannot see it. That is the thing. | There is a field behind the barn. If he is putting it down, it will be there.'
'p686-alleyway-robbery' = 'It is the third time this month in that alley. | Two of them, and they took his wallet and his watch. | You can see the whole alley from my window. That is how I watch it.'
'p686-area-surveillance' = 'It happens most nights about this time. | They come in a dark car and they are gone in ten minutes. | I am not standing at my window while you are parked on my road.'
'p686-attempted-break-in' = 'I put the light on and he ran. | He had a bar with him. I saw it through the glass. | He went over the back fence and into the alley.'
'p686-car-bomb' = 'The wires were hanging down by the pedals. | I did not touch anything. I called you from across the road. | I do not know whose it is. It has been there since yesterday.'
'p686-custom-pursuit' = 'It is the second time tonight it has gone past here. | Same plate, same driver. He is doing laps. | Do what you have to do. I am not going anywhere.'
'p686-disorientated-individual' = 'He has been walking in the road for twenty minutes. | I asked him if he was all right and he did not answer me. | He is not drunk. I have seen drunk and this is not that.'
'p686-fare-dodger' = 'I am not paying because the machine is broken. That is not my problem. | I am not getting off. I paid to get on this bus. | Call whoever you like. I am sat here.'
'p686-high-risk-escort' = 'The transfer is at four and it has to be a two unit escort. | He has previous for going for the door on the highway. | If you are not happy with the route we go the long way. I would rather be late.'
'p686-kidnapping' = 'They put him in the back of a blue van and drove off. | I am following it. Two cars back, that is all. | It has turned towards the docks. It is going towards the docks.'
'p686-lane-closure' = 'I need that lane shut for the recovery. Fifteen minutes. | The traffic will be a mile back by the time we are done. | Cones out before the lorry arrives, not after.'
'p686-large-vehicle-pursuit' = 'The HGV has not stopped and the driver is looking at us. | You cannot PIT that. Nobody is PIT-ing that. | We need a stinger, and we need it before the junction.'
'p686-offensive-weapon' = 'It is a machete and he is walking down the middle of the road with it. | He has not threatened anybody. Everybody has just moved out of his way. | Two cars have gone past him and neither of them stopped.'
'p686-photography' = 'I am filming a building. That is not a crime. | It is a public pavement and I am allowed to stand on a public pavement. | You can look at the camera. There is a building on it. Nothing else.'
'p686-property-checkup' = 'The alarm has been going forty minutes and nobody can reach the keyholder. | The front is secure. It is the back that worries me. | I am not going in through the back on my own.'
'p686-protest' = 'We have a permit to be here and we are not moving. | Nobody has blocked anything. The pavement is clear behind us. | There are two hundred people here and all of them are peaceful. Do not change that.'
'p686-solicitation' = 'I am waiting for somebody. That is all I am doing. | I have been on this corner twenty minutes and I have not spoken to a soul. | You have got nothing. Everybody on this street knows it.'
'p686-sting-operation' = 'The buy is set for ten minutes from now. | Two of them on a scooter, same as last week. | Nobody moves until I say so. That is the whole point of this.'
'p686-stolen-item' = 'It is in the window. That is the exact one from my house. | It has an engraving on the back. Look at the engraving. | I have the papers at home. I can prove it is mine.'
'p686-stolen-pedal-bike' = 'I left it outside for two minutes and it was gone. | Green frame, white seat. That is distinctive. | There is a camera on the shop front. It should have all of it.'
'p686-subway-disturbance' = 'One man going along the platform shouting and pushing people. | We have held the trains so nobody is stuck down here with him. | He has gone down onto the track. He is on the track now.'
'p686-suspected-stalker' = 'Same man, same car, every morning this week. | He parks across the road and he just sits there. | I have the plate and I have the dates. It is all written down.'
'p686-swat-raid' = 'They are not answering and the door is barricaded from the inside. | One confirmed male, possibly two. | Nobody goes through that door until you say the word.'
'p686-terrorist-attack' = 'It is still going on. Multiple callers and every one of them saying shots. | I need everything you have and I need it now. | Do not go in on your own. Do you hear me, do not go in on your own.'
'p686-traffic-stop-backup' = 'I have one male out of the vehicle and he is compliant. | It is the passenger who is the problem. He will not get out. | I am on the shoulder. Come up on my side.'
'p686-vehicle-on-sidewalk' = 'He went up the pavement to get past the queue. | There were people on that pavement. A woman with a pram stepped into the road. | He turned off at the next junction. He is still local.'
'p686-vip-evacuation' = 'The route has to be clear before the convoy moves. | I need a left turn and a clear run to the motorway. | If the route is not clear the convoy does not move. That is the whole of it.'

# ============================================================ Park Rangers
'sapr-bear-sighting' = 'It came into the camp about an hour ago and it has not gone far. | Nobody has been hurt. Everybody is in their tents. | It went for the food bin and then it just sat down.'
'sapr-campers-fire' = 'It is not ours. It was already going when we got here. | There are three tents inside the ring and nobody in them. | The wind is taking it towards the trees.'
'sapr-climber-stuck' = 'He is below the ridge and he will not move. | He says his leg has gone. He is talking, which is something. | You need the rope team. There is no way up that face otherwise.'
'sapr-drone-over-park' = 'It is over the nesting area. That is closed this month. | It has been up twenty minutes and it is filming the whole valley. | The operator is somewhere by the car park. That is where they always are.'
'sapr-dumped-chemicals' = 'Six drums and two of them are leaking. | It is at the beauty spot, right beside the picnic table. | Do not touch them. That is my advice and I am sticking to it.'
'sapr-dumping-park' = 'Somebody tipped a trailer load at the trailhead in the night. | There is no vehicle and there is nobody here now. | It is the third time this year at the same spot.'
'sapr-fire-lookout' = 'Smoke, three ridges over, and it is not camp smoke. | I have it from the tower and it is building. | If it gets over that ridge there is nothing to stop it.'
'sapr-illegal-campfire' = 'It is a fire ban. There are signs at every gate. | Three of them sat round it and they have been drinking. | They have seen me and they are not putting it out.'
'sapr-illegal-fishing' = 'They have got a net across the narrow end. | It is a protected lake and that net has been in since dusk. | Two of them and a boat. They know exactly what they are doing.'
'sapr-illegal-tour' = 'Twelve of them and a guide, all well off the marked path. | They are paying for it, that is why he does it. | They are heading for the falls, and the falls are closed.'
'sapr-injured-horse' = 'She is down at the bridge and she will not get up. | The rider is sat with her. The rider is fine, the horse is not. | There is a vet coming from town. That is an hour away.'
'sapr-injured-wildlife' = 'It is a deer and it is still alive on the verge. | Traffic is slowing right down to look at it. | Nobody has hit it twice. Not yet.'
'sapr-litter-fire' = 'The bin at the picnic area is alight and it has taken the table. | There is nobody here. It is shut for the season. | It is going towards the gorse and the gorse is dry.'
'sapr-lost-walker' = 'I am on a path but I do not know which one. | I can see a ridge to my left and water below it. | My battery is nearly gone. I am going to have to stop talking.'
'sapr-missing-swimmer' = 'He went in off the rocks half an hour ago. | His towel and his keys are still on the rock. | Nobody has seen him come out of the water.'
'sapr-off-roading' = 'There are two of them and neither is on the trail. | They have been across the protected ground. You can see the tracks. | They are heading up the fire road. That is where it comes out.'
'sapr-poaching-park' = 'Shots, after closing, from the treeline. | That is not a licensed hunter. The season ended a month ago. | Assume they are armed and assume they will run.'
'sapr-rockfall' = 'The trail is blocked and there are people above it. | Four of them, and they cannot come down this way. | It is still moving. Every few minutes another one comes down.'
'sapr-snake-bite' = 'It was on the path, in the shade. | It went for my calf and it was gone before I saw it properly. | I have put my leg up and I have not moved since.'
'sapr-tourist-lost' = 'There are four of us and two of them are children. | The phone is at four per cent. I am going to lose it. | We came off the trail where the sign was missing.'

# ============================================================ Highway Patrol
'sahp-abandoned-vehicle' = 'It has been there five days. It is not mine and it is not anybody round here. | No plates on it and the doors are unlocked. | Nobody has touched it. I have been watching it out of the window.'
'sahp-abnormal-load' = 'It is over the limit on width and it needs an escort to the county line. | Five miles an hour, and there is no way round it on that road. | One unit in front and one behind. That is what we agreed.'
'sahp-breakdown' = 'It is in a live lane with the hazards on and I cannot get it moving. | I am behind the barrier. I am not standing in the lane. | The recovery is twenty minutes out. That is a long twenty minutes.'
'sahp-breakdown-night' = 'There are no lights on it at all. None. | It is right over the crest and you do not see it until you are on top of it. | I have put my own car behind it with the lights on. That is all I can do.'
'sahp-bridge-stopped' = 'He is parked on the bridge and he is stood at the rail. | He has not done anything. He is just stood there looking at the water. | I am keeping well back. That is why I called you.'
'sahp-bus-collision' = 'I hit my head on the handrail. I was standing up. | The bus went into the back of the car and everybody came forward. | There are people in the aisle and two of them are not getting up.'
'sahp-cow-motorway' = 'It is on the carriageway and the traffic is doing seventy at it. | Two cars have already gone onto the hard shoulder to miss it. | I am not going out there on foot. Not for that.'
'sahp-cyclist-collision' = 'My shoulder. I went over the bonnet. | I had lights on and a jacket on. Ask the driver. | I am not moving off this kerb until somebody tells me I can.'
'sahp-debris' = 'It is across both lanes and nobody knows where it came from. | It is metal. Something has come off something. | People are swerving at the last second. It is going to happen.'
'sahp-drunk-driver' = 'I am two cars behind it and it cannot hold a lane. | It was twenty, then sixty, then twenty again. | It has just clipped the kerb. It is on the kerb now.'
'sahp-failing-to-stop' = 'It failed to stop about two minutes ago and it went east. | I did not get the driver. Only the vehicle. | I am not pursuing on my own. Not without authorisation.'
'sahp-fuel-spill' = 'It is diesel and it is across two lanes. | The spill came off the truck and the truck has gone. | There is a van coming up that hill. Somebody is going to slide.'
'sahp-hit-and-run' = 'It was a white van and it did not slow down. | The pedestrian is in the road and he is talking. | The van went north. It went north and it was still accelerating.'
'sahp-insecure-load' = 'It is shedding off the back every hundred yards. | It is timber and there is a lot of it. | The driver has pulled onto the shoulder and he is looking at it.'
'sahp-jackknife' = 'The trailer is across both lanes and the cab is in the barrier. | The driver is out and he is walking about. He is shaken. | Nobody is getting past. That is the top and bottom of it.'
'sahp-motorcycle-collision' = 'I am all right. I am all right. Is the bike all right? | He pulled out in front of me. He did not look. | I have got a cut on my arm. Nothing else. I am fine.'
'sahp-motorcycle-racing' = 'Three of them and they are doing well over a hundred. | They are going through the traffic like it is stood still. | They have just gone past a junction and they did not slow down for it.'
'sahp-overheight' = 'It has hit the bridge and it is wedged under it. | The roof of the trailer has gone back into the cab. | The driver is out and he is on the phone to his firm.'
'sahp-overloaded-pickup' = 'It is sitting on the bump stops and the load is not strapped. | There are sheets of steel on it and nothing holding them down. | It came past me and the whole truck was moving sideways.'
'sahp-overweight-lorry' = 'He failed the weight check and he was not polite about it. | I have got him stopped and he is arguing with me about the paperwork. | I need a second unit before I start on the load.'
'sahp-road-rage' = 'He cut me up at the junction and then he brake checked me. | We both got out. Neither of us threw anything. | He has gone back to his car. That is the part I am watching.'
'sahp-roadworks' = 'He went straight through the closure and the lads had to jump. | It is forty miles an hour through there and he did not brake. | The signs were up. They have been up all morning.'
'sahp-speeding-convoy' = 'Five of them, all running together. | They are changing lanes as a block. That is deliberate. | The cars are modified. You can hear them from here.'
'sahp-speeding-stop-backup' = 'I have one vehicle stopped and two occupants. | The driver is fine. It is the passenger who keeps reaching under the seat. | Second unit, come up on the offside.'
'sahp-stolen-plate' = 'Both plates were taken in the night and both were left on the ground. | I did not hear anything. Not a thing. | It is a clean removal. That is what they do now.'
'sahp-street-racing' = 'Two cars side by side at well over a hundred. | They have gone up the road towards the retail park. | There are people stood on the verge watching them. That is the worst of it.'
'sahp-truck-collision' = 'Two lorries and they are blocking everything. | One driver is out and the other one is still in the cab. | There is diesel on the road and a trailer across two lanes.'
'sahp-tunnel-breakdown' = 'There is a car stopped inside the tunnel and there is smoke coming off it. | The traffic behind is still coming in. Nobody has shut it off. | Get the tunnel closed. That is the thing that matters.'
'sahp-tunnel-fire' = 'It is alight inside and cars are still going past it. | The smoke is going along the roof. It is filling the tunnel. | Nobody has shut the tunnel at either end.'
'sahp-wrong-way' = 'It is coming straight at people with its headlights on. | Three callers now and every one of them saying the same thing. | Somebody is going to be killed. Somebody needs to shut that road.'
'sahp-wrong-way-motorway' = 'It is on the wrong side of the barrier and it is not slowing down. | It has gone past two junctions and nobody is stopping it. | Shut the carriageway. Shut it now.'
}
